# .travis.yml for Adafruit IO Python Client Library

dist: trusty
sudo: false
language: python
python:
    - "3.6"

cache:
    pip: true

before_install:
  #pip install -r requirements.txt

install:
  - python setup.py install
  - pip install pylint Sphinx sphinx-rtd-theme
  - pip install .

script:
  # run /tests/
  - python -m unittest discover
  # build library docs
  - cd docs && sphinx-build -E -W -b html . _build/html