language: python
dist: trusty
sudo: required
python:
- '3.6'
cache:
  pip: true
install:
- python3 setup.py install
- pip3 install pylint Sphinx sphinx-rtd-theme
- pip3 install .
script:
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
- cd tests/
- python3 -m unittest discover
deploy:
  - provider: pypi
    user: adafruit-travis
    password:
      secure: WYAvV+71bL0EjUV2MMmIuf/P0RNLBUGiHcjFZnvRhZriOP7MPSXoePG31k309mWE/0e26gxPWdZH/zpWEm5Vzb2RbGGvTypjD9u/c5HJqcLohVy9mPCqgvkJNQi+Sqe0u4XsMHMaueZd8vry+MLH5+h6Py7fjx/4MVZKHLxHdMI=
    on:
      tags: true
