# .travis.yml for Adafruit IO Python Client Library
language: python
dist: trusty
sudo: required

python:
    - "3.6"

cache:
    pip: true

before_install:
  - git clone https://github.com/adafruit/io-client-python.git
  - cd io-client-python/tests
  - git checkout api-v2

install:
  - python setup.py install
  - pip install pylint Sphinx sphinx-rtd-theme
  - pip install .

script:
  # clone fresh 
  - cd home/travis/build/adafruit/io-client-python/tests
  - python -m unittest discover
  # build library docs
  - cd docs && sphinx-build -E -W -b html . _build/html