# .travis.yml for Adafruit IO Python Client Library
language: python
dist: trusty
sudo: required

python:
    - "3.4.0"

cache:
    pip: true


install:
  - python setup.py install
  - pip install pylint Sphinx sphinx-rtd-theme
  - pip install .

script:
  - cd docs && sphinx-build -E -W -b html . _build/html
  - cd ..
  - cd tests/
  - python -m unittest discover