name: Build-CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install library
      run: python3 setup.py install
    - name: Secret
      env: 
        secret_io_key: ${{ secrets.CI_IO_KEY }}
        secret_io_user: ${{ secrets.CI_IO_USERNAME }}
      run: cd tests/
    - name: Run all unittests
      run: |
        cd tests/
        python3 -m unittest discover